sudo: required
cache:
  directories:
    - $HOME/.m2
language: java
services:
  - docker
jdk:
  - openjdk8
os:
  - linux
before_install:
  - sed -i "s|\[JDK8_HOME\]|$JAVA_HOME|g" ci/toolchains.xml
install:
  - mvn -t ci/toolchains.xml -B -V install -DskipTests
before_script:
  - mvn -t ci/toolchains.xml -B -V clean
script:
  - mvn -t ci/toolchains.xml -B -V test
after_success:
  - mvn -t ci/toolchains.xml -B -V -s ci/settings.xml deploy -DskipTests
