name: build

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    name: Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn --settings ci/settings.xml --toolchains ci/toolchains.xml --batch-mode --show-version --no-transfer-progress clean verify deploy
